services:
  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      - NACOS_AUTH_IDENTITY_KEY=example
      - NACOS_AUTH_IDENTITY_VALUE=example
      - NACOS_AUTH_TOKEN=U2VjcmV0S2V5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5
    ports:
      - "18848:8848"
      - "19848:9848"
    restart: always

  redis:
    image: redis:latest
    container_name: redis-standalone
    ports:
      - "6379:6379"
    restart: always

  elasticsearch:
    image: elasticsearch:8.19.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "19200:9200"
      - "19300:9300"
    restart: always

  recommendation-service:
    build: ./recommendation-service
    container_name: recommendation-service
    ports:
      - "5000:5000"
    environment:
      - DB_URL=mysql+pymysql://root:123456@host.docker.internal:3306/goodshare
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  
  # mysql:
  #   image: mysql:8.4
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: goodshare
  #   ports:
  #     - "3306:3306"
