services:
  nacos:
    image: nacos/nacos-server:v3.1.1
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      - NACOS_AUTH_IDENTITY_KEY=example
      - NACOS_AUTH_IDENTITY_VALUE=example
      - NACOS_AUTH_TOKEN=U2VjcmV0S2V5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always

  redis:
    image: redis:latest
    container_name: redis-standalone
    ports:
      - "6379:6379"
    restart: always
  
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: goodshare
  #   ports:
  #     - "3306:3306"
