server:
  port: 8082

spring:
  application:
    name: crawler-service
  datasource:
    url: jdbc:mysql://localhost:3306/goodshare?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848

logging:
  level:
    root: INFO
    yan.goodshare.crawler: DEBUG
